### ISSUE TITLE
[Bug]: entry is not iterable when running storybook

### ISSUE THREAD

**Issue by echarles** [Py4Js/pyscript-react#362]
### What happened?

I am trying the latest HEAD revision of this repo. The following works well on my env.

```
yarn --ignore-engines
yarn run build --target npm
yarn run test
```

The running `yarn storybook`, I hit ` [vite] Internal server error: entry is not iterable`(see details below).

### Relevant log output

```shell
│   A new version (6.5.10) is available!            │
│                                                   │
│   Upgrade now: npx sb@latest upgrade              │
│                                                   │
│   Read full changelog: https://git.io/fhFYe       │
│                                                   │
╰───────────────────────────────────────────────────╯
08:30:26 [vite] Internal server error: entry is not iterable
      at Object.config (/Users/echarles/datalayer-platform/ext/pyscript-react/node_modules/@storybook/addon-interactions/preset.js:2:14)
      at /Users/echarles/datalayer-platform/ext/pyscript-react/node_modules/@storybook/core-common/dist/cjs/presets.js:279:28
      at async generateModernIframeScriptCode (/Users/echarles/datalayer-platform/ext/pyscript-react/node_modules/@storybook/builder-vite/codegen-modern-iframe-script.ts:10:25)
      at async Object.load (/Users/echarles/datalayer-platform/ext/pyscript-react/node_modules/vite/dist/node/chunks/dep-97cb3622.js:39268:32)
      at async doTransform (/Users/echarles/datalayer-platform/ext/pyscript-react/node_modules/vite/dist/node/chunks/dep-97cb3622.js:49951:24)
info 💡 Skipping library/components/base/PyScript/PyScript.story.js: NoMetaError: CSF: missing default export /Users/echarles/datalayer-platform/ext/pyscript-react/library/components/base/PyScript/PyScript.story.js (line 1, col 0)
info 
info More info: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
```

### Do you want to be assigne to this issue?

- [ ] I want to be assigne to this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShootGan** [comment]
You can try to run this from the development branch.
Sorry, that you have to wait for an answer for so long.
Best regards,
Paweł
